n = int(input('O número escolhido é: '))
print('Multiplicado por 1, seria: {}'.format((n*1)))
print('Multiplicado por 2, seria: {}'.format((n*2)))
print('Multiplicado por 3, seria: {}'.format((n*3)))
print('Multiplicado por 4, seria: {}'.format((n*4)))
print('Multiplicado por 5, seria: {}'.format((n*5)))
print('Multiplicado por 7, seria: {}'.format((n*7)))
print('Multiplicado por 8, seria: {}'.format((n*8)))
print('Multiplicado por 9, seria: {}'.format((n*9)))
print('Multiplicado por 10, seria {}'.format((n*10)))
